### ISSUE TITLE
Getting TektonInstallerset through omc is breaking

### ISSUE THREAD

**Issue by PuneetPunamiya** [gmeghnag/omc#111] opened 2023-07-26 15:23 UTC
omc command fails while retrieving TektonInstallerset

* Actual Behavior

```bash=
╰─ omc get tektoninstallersets.operator.tekton.dev
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1a0 pc=0x2a10737]

goroutine 1 [running]:
github.com/gmeghnag/omc/pkg/tablegenerator.GenerateCustomResourceTable({0x0})
	/home/Puneet/openshift-pipelines/omc/pkg/tablegenerator/tablegenerator.go:126 +0xb37
github.com/gmeghnag/omc/cmd/get.handleObject({0x0})
	/home/Puneet/openshift-pipelines/omc/cmd/get/get.go:407 +0x1092
github.com/gmeghnag/omc/cmd/get.getClusterScopedResources({0xc00081c5d0, 0x13}, {0xc00081c588, 0x13}, 0xc00088e7e0)
	/home/Puneet/openshift-pipelines/omc/cmd/get/get.go:333 +0x5f2
github.com/gmeghnag/omc/cmd/get.glob..func1(0x4ae6d20?, {0xc0003e4700?, 0x1?, 0x1?})
	/home/Puneet/openshift-pipelines/omc/cmd/get/get.go:107 +0x4bb
github.com/spf13/cobra.(*Command).execute(0x4ae6d20, {0xc0003e46c0, 0x1, 0x1})
	/home/Puneet/openshift-pipelines/omc/vendor/github.com/spf13/cobra/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x4ae8140)
	/home/Puneet/openshift-pipelines/omc/vendor/github.com/spf13/cobra/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/Puneet/openshift-pipelines/omc/vendor/github.com/spf13/cobra/command.go:968
main.main()
	/home/Puneet/openshift-pipelines/omc/main.go:24 +0x25

```

* Expected Behaviour

```bash=
─ omc get tektoninstallersets.operator.tekton.dev
NAME                                             READY   REASON
addon-custom-clustertask-x7crj                   True    
addon-custom-communityclustertask-5vzls          True    
addon-custom-consolecli-kdttk                    True    
addon-custom-openshiftconsole-87rps              True    
addon-custom-pipelinestemplate-jbx88             True    
addon-custom-triggersresources-fn6z7             True    
addon-versioned-clustertasks-1.11-kkdwf          True    
chain-bcb4k                                      True    
chain-secret-8v84c                               True    
openshiftpipelinesascode-main-deployment-psdrb   True    
openshiftpipelinesascode-main-static-v9rgv       True    
openshiftpipelinesascode-post-c9chb              True    
pipeline-main-deployment-bd27t                   True    
pipeline-main-static-mq4zz                       True    
pipeline-post-wj7ff                              True    
pipeline-pre-qtkm8                               True    
rhosp-rbac-bv67w                                 True    
tektoncd-pruner-szwlk                            True    
trigger-main-deployment-swzn5                    True    
trigger-main-static-7bx4w                        True    
validating-mutating-webhoook-bjc6g               True    

```

**Comment by gmeghnag** [comment] 2023-07-26 16:47
closing as duplicate of #109

**Closed by gmeghnag** 2023-07-26 16:47 UTC
